services:
  kls_bridge:
    build:
      context: .
      no_cache: true
    container_name: kls_bridge
    restart: unless-stopped
    user: "0"
    command:
      - '-stats=false'
      - '-karlsen=host.docker.internal:38110'
    ports:
      - 1555:1555
      - 2114:2114
    extra_hosts:
      - host.docker.internal:host-gateway
